#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - avahi-daemon
  - python3-pip
  - nginx

runcmd:
  - python3 -m pip install localstack==2.0.2
  - systemctl start nginx.service
  - systemctl enable nginx.service

